### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by MacGyver27** [adolfintel/speedtest#182]
Hi, its me again.. 

We were in touch in the past about the issue setting up the telemetry.

## Server
- speedtest.aronmgv.com - contains telemetry settings
- speedtest.aronmgv.com/___whatever-file-in-this-git-distro___
- speedtest.aronmgv.com/phpinfo.php - php info
- speedtest.aronmgv.com/test.html - copy from: http://speedtest.fdossena.com/

I tried 2 approaches:
- using sqlite - not much config done here
- using postgres - here verified I have pgsql plugin in the container (confirmed via info function on .php page)

Both scenarios result into `PDOException` error:
sqlite (`telemetry.php?r=0.5873636724359883`):
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in /var/www/html/telemetry/telemetry.php:25 Stack trace: #0 /var/www/html/telemetry/telemetry.php(25): PDO->__construct('sqlite:../../te...') #1 {main} thrown in /var/www/html/telemetry/telemetry.php on line 25
```
postgres():
```
Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/telemetry/telemetry.php:53 Stack trace: #0 /var/www/html/telemetry/telemetry.php(53): PDO->__construct('pgsql:host=post...') #1 {main} thrown in /var/www/html/telemetry/telemetry.php on line 53
```

## Client
any

Any input is much appreciated.. Michal

**Comment by MacGyver27** [comment]
Finally solved the issue with postgres.

Had to create my own Dockerfile to build image from. Don't really understand why you provide functionality which is missing dependencies in the image itself though.. Kinda counterproductive isn't it?

The working dockerfile:
```
FROM php:7.2.12-apache-stretch
EXPOSE 80
RUN apt-get update \
  && apt-get install --no-install-recommends -y libpq-dev \
  && docker-php-ext-install pgsql \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
WORKDIR /var/www/html/
COPY . /var/www/html
RUN ln -s /var/www/html /var/www/html/speedtest
CMD ["/usr/local/bin/apache2-foreground"]
```
thanks
