### ISSUE TITLE
Cross origin worker

### ISSUE THREAD

**Issue by fotisolgr** [adolfintel/speedtest#32]
Is it possible to create a web worker calling speedtest_worker.js from another domain?
i.e. var worker=new Worker(https://path/to/speedtest_worker.js);

**Comment by adolfintel** [comment]
I haven't tried, but it should work if you add CORS headers to your page.
One of the forks of this project used them to have multiple points of test, but has not sent a pull request yet.

**Comment by fotisolgr** [comment]
**This is my HTML page:**
```
<!DOCTYPE html>
<html>
<head>
<title>Speed worker</title>

	<script type="text/javascript" src="jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript" hostingWebsite="http" id="settings" agentIp="127.0.0.1" workerPath="" cookieTimeInMinutes="0.01"
				 src="speedworker-post.js"></script>
</head>
<body>

<h1>Sample HTTP page for WiFiMon measurements using speedtest_worker.js</h1>

 </body>
</html>
```
**And this is the code im using to create my worker:**
```
if (typeof document.getElementById("settings").getAttribute("workerPath") === 'undefined' || document.getElementById("settings").getAttribute("workerPath") == '') {

	var worker_path = 'https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedtest_worker.js';
	var w=new Worker(worker_path); //create new worker}

```
**When I'm running the above HTML page I'm getting this error:**
```
Uncaught DOMException: Failed to construct 'Worker': Script at 'https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedtest_worker.js' cannot be accessed from origin 'http://localhost'.
    at http://localhost/speedworker-post.js:8:8
```
**Any thoughts?**

**Also I changed the way I'm trying to create the web worker by trying the blob method:**
```

if (typeof document.getElementById("settings").getAttribute("workerPath") === 'undefined' || document.getElementById("settings").getAttribute("workerPath") == '') {

var blob = new Blob(['importScripts("https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedtest_worker.js")'], {type: 'text/javascript'});
var w=new Worker(URL.createObjectURL(blob));
```
**But I'm getting the following error:**
```
Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at getIp (https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedtest_worker.js:134:6)
    at https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedtest_worker.js:103:3
```
**Any thoughts?**

**Comment by adolfintel** [comment]
As I said, your server must send CORS headers to allow cross-domain requests. See this: https://enable-cors.org/server.html

**Comment by fotisolgr** [comment]
**CORS is enabled. Into my apache2.conf i have these lines:**
```
<Files ~ "\.(htm|html|css|js|php|gif|jpg|swf)$">
  Header always set Access-Control-Allow-Origin "*"
  Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
  Header always set Access-Control-Max-Age "1000"
  Header always set Access-Control-Allow-Headers "*"
</Files>
```

**Comment by adolfintel** [comment]
Please see this fork (and maybe contact the guy who made it): https://github.com/axiros/speedtest
His changes will be integrated soon, including CORS.

**Comment by fotisolgr** [comment]
The problem was solved much easier than I thought. I just modified my HTML page into that:
```
!DOCTYPE html>
<html>
<head>
<title>Speed worker</title>
<iframe src="https://vm3-gn3-sa2t5.vm.grnet.gr/wifimon/js/speedtest/speedworker.html" style="visibility: hidden;"></iframe>

</head>
<body>

<h1>Sample HTTP page for WiFiMon measurements using speedtest_worker.js</h1>

 </body>
</html>
```

**So I'm using an iframe to bypass the cross-origin error I was getting.**

**Comment by adolfintel** [comment]
Yeah, that was a solution that I proposed to that guy who later used CORS.
No idea why it's not working for you though.
